services:
  web:
    build: .
    ports:
      - "10200:80"
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./direct-disclosure.page.gd/htdocs:/var/www/html/direct
      - ./progressive-disclosure.page.gd/htdocs:/var/www/html/progressive
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: penilaian_akademik
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "10201:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./if0_40090928_penilaian_akademik.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webnet

volumes:
  db_data:


networks:
  webnet:
    external: true